import { App, PluginSettingTab, Setting, Notice } from "obsidian";
import TermuxBridgePlugin from "./main";

export interface TermuxBridgeSettings {
	serverPort: string;
	serverToken: string;
}

export const DEFAULT_SETTINGS: TermuxBridgeSettings = {
	serverPort: '8085',
	serverToken: ''
}

// The Python Server Script and Auto-Start Command are now handled by external scripts.

export class TermuxBridgeSettingTab extends PluginSettingTab {
	plugin: TermuxBridgePlugin;

	constructor(app: App, plugin: TermuxBridgePlugin) {
		super(app, plugin);
		this.plugin = plugin;
	}

	display(): void {
		const {containerEl} = this;
		containerEl.empty();

		containerEl.createEl('h1', {text: 'Termux Bridge Configuration'});

		// --- Connection Settings ---
		new Setting(containerEl)
			.setName('Server Port')
			.setDesc('The local port Termux is listening on.')
			.addText(text => text
				.setPlaceholder('8085')
				.setValue(this.plugin.settings.serverPort)
				.onChange(async (value) => {
					this.plugin.settings.serverPort = value;
					await this.plugin.saveSettings();
				}));

		new Setting(containerEl)
			.setName('Security Token')
			.setDesc('The token generated by the install script (check ~/.obsidian_termux_token).')
			.addText(text => text
				.setPlaceholder('Paste your token here')
				.setValue(this.plugin.settings.serverToken)
				.onChange(async (value) => {
					this.plugin.settings.serverToken = value;
					await this.plugin.saveSettings();
				}));

		new Setting(containerEl)
			.setName('Test Connection')
			.setDesc('Sends a test command to check if the bridge is working.')
			.addButton(btn => btn
				.setButtonText('Test Now')
				.onClick(async () => {
					await this.plugin.testConnection();
				}));

		containerEl.createEl('hr');

		// --- Setup Guide ---
		containerEl.createEl('h2', {text: 'Setup Guide'});
		containerEl.createEl('p', {text: 'Run these commands in Termux to manage the bridge server.'});

		// Install Script
		new Setting(containerEl)
			.setName('Install / Update')
			.setDesc('Installs Python, creates the server script, and sets up auto-start.')
			.addButton(btn => btn
				.setButtonText('Copy Install Command')
				.setCta()
				.onClick(() => {
					const cmd = 'curl -sL https://raw.githubusercontent.com/abduznik/obsidian-shell-termux/main/scripts/install.sh | bash';
					navigator.clipboard.writeText(cmd);
					new Notice('Install command copied!');
				}));

		// Uninstall Script
		new Setting(containerEl)
			.setName('Uninstall')
			.setDesc('Removes the server script.')
			.addButton(btn => btn
				.setButtonText('Copy Uninstall Command')
				.onClick(() => {
					const cmd = 'curl -sL https://raw.githubusercontent.com/abduznik/obsidian-shell-termux/main/scripts/uninstall.sh | bash';
					navigator.clipboard.writeText(cmd);
					new Notice('Uninstall command copied!');
				}));

		containerEl.createEl('p', {text: 'Note: The install script will add an auto-start check to your ~/.bashrc. If you uninstall, you may want to manually remove that block from ~/.bashrc.'});
	}
}