import { App, PluginSettingTab, Setting, Notice } from "obsidian";
import TermuxBridgePlugin from "./main";

export interface TermuxBridgeSettings {
    serverPort: string;
    serverToken: string;
}

export const DEFAULT_SETTINGS: TermuxBridgeSettings = {
    serverPort: '8085',
    serverToken: ''
}

export class TermuxBridgeSettingTab extends PluginSettingTab {
    plugin: TermuxBridgePlugin;

    constructor(app: App, plugin: TermuxBridgePlugin) {
        super(app, plugin);
        this.plugin = plugin;
    }

    display(): void {
        const {containerEl} = this;
        containerEl.empty();

        new Setting(containerEl)
            .setName('Configuration') 
            .setHeading();

        new Setting(containerEl)
            .setName('Local port')
            .setDesc('The port the local server listens on.')
            .addText(text => text
                .setPlaceholder('8085')
                .setValue(this.plugin.settings.serverPort)
                .onChange(async (value) => {
                    this.plugin.settings.serverPort = value;
                    await this.plugin.saveSettings();
                }));

        new Setting(containerEl)
            .setName('Security token')
            .setDesc('The token generated by the setup script.')
            .addText(text => text
                .setPlaceholder('Paste your token here')
                .setValue(this.plugin.settings.serverToken)
                .onChange(async (value) => {
                    this.plugin.settings.serverToken = value;
                    await this.plugin.saveSettings();
                }));

        new Setting(containerEl)
            .setName('Test connection')
            .setDesc('Sends a test command to check if the bridge is working.')
            .addButton(btn => btn
                .setButtonText('Test connection')
                .onClick(async () => {
                    await this.plugin.testConnection();
                }));

        new Setting(containerEl)
            .setName('Setup')
            .setHeading();
            
        containerEl.createEl('p', {text: 'Run these commands in your terminal to manage the bridge server.'});

        new Setting(containerEl)
            .setName('Install script')
            .setDesc('Installs dependencies and creates the server script.')
            .addButton(btn => btn
                .setButtonText('Copy to clipboard')
                .setCta()
                .onClick(() => {
                    const cmd = 'curl -sL https://raw.githubusercontent.com/abduznik/obsidian-shell-termux/main/scripts/install.sh | bash';
                    void navigator.clipboard.writeText(cmd);
                    new Notice('Command copied!');
                }));

        new Setting(containerEl)
            .setName('Remove server')
            .setDesc('Removes the server script.')
            .addButton(btn => btn
                .setButtonText('Copy to clipboard')
                .onClick(() => {
                    const cmd = 'curl -sL https://raw.githubusercontent.com/abduznik/obsidian-shell-termux/main/scripts/uninstall.sh | bash';
                    void navigator.clipboard.writeText(cmd);
                    new Notice('Command copied!');
                }));

        // FIX: Removed "Note:" to satisfy sentence case, restored ~/.bashrc
        containerEl.createEl('p', {text: 'The install script will add an auto-start check to your ~/.bashrc file.'});
    }
}